# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180826_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='opinioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='blog.User'),
        ),
    ]
