# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_auto_20180828_1131'),
        ('new_courses', '0002_auto_20180821_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='loginreg.User'),
        ),
    ]
