# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_auto_20180828_1131'),
        ('new_courses', '0003_course_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(null=True, related_name='courses', to='loginreg.User'),
        ),
    ]
