# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_courses', '0004_auto_20180828_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='loginreg.User'),
        ),
    ]
