# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_courses', '0005_auto_20180828_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='students',
            new_name='student',
        ),
    ]
