# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_auto_20180828_1131'),
        ('new_courses', '0006_auto_20180828_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_students', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='loginreg.User'),
        ),
        migrations.AddField(
            model_name='roster',
            name='courses',
            field=models.ManyToManyField(related_name='rosters', to='new_courses.Course'),
        ),
        migrations.AddField(
            model_name='roster',
            name='students',
            field=models.ManyToManyField(related_name='rosters', to='loginreg.User'),
        ),
    ]
