# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_auto_20180828_1131'),
        ('new_courses', '0011_auto_20180828_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='registered_courses',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='registered_students',
        ),
        migrations.AddField(
            model_name='roster',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='new_courses.Course'),
        ),
        migrations.AddField(
            model_name='roster',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='loginreg.User'),
        ),
    ]
