# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_courses', '0012_auto_20180828_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='registered_users',
        ),
        migrations.AddField(
            model_name='course',
            name='registered_users',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
