# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_auto_20180828_1131'),
        ('new_courses', '0014_roster_registered_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='users',
        ),
        migrations.AddField(
            model_name='roster',
            name='roster_courses',
            field=models.ManyToManyField(null=True, related_name='rosters', to='new_courses.Course'),
        ),
        migrations.AddField(
            model_name='roster',
            name='roster_users',
            field=models.ManyToManyField(null=True, related_name='rosters', to='loginreg.User'),
        ),
    ]
