# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_courses', '0015_auto_20180828_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='roster_courses',
        ),
        migrations.AddField(
            model_name='roster',
            name='course',
            field=models.ManyToManyField(related_name='rosters', to='new_courses.Course'),
        ),
    ]
