# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_auto_20180828_1131'),
        ('new_courses', '0016_auto_20180828_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='roster_users',
        ),
        migrations.AddField(
            model_name='roster',
            name='user',
            field=models.ManyToManyField(related_name='rosters', to='loginreg.User'),
        ),
    ]
