# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_courses', '0017_auto_20180828_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AlterField(
            model_name='roster',
            name='course',
            field=models.ManyToManyField(blank=True, to='new_courses.Course'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='user',
            field=models.ManyToManyField(blank=True, to='loginreg.User'),
        ),
    ]
