# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 02:51
from __future__ import unicode_literals

import apps.reglogin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, validators=[apps.reglogin.models.validateLengthGreaterThanTwo]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, validators=[apps.reglogin.models.validateLengthGreaterThanTwo]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, validators=[apps.reglogin.models.validateLengthGreaterThanTwo]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, validators=[apps.reglogin.models.validateLengthGreaterThanTwo]),
        ),
    ]
