# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginreg', '0001_initial'),
        ('new_courses', '0002_auto_20180821_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='new_courses.Course')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='loginreg.User')),
            ],
        ),
    ]
