# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0006_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.TextField(max_length=1000),
        ),
    ]
