# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0009_auto_20180818_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='bookreviewed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookreview.Book'),
        ),
    ]
