# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0011_auto_20180830_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
