# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0007_auto_20180817_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
