# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0002_user_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
