# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0003_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_level',
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
