# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0004_auto_20180905_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
