# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180823_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='users',
            new_name='user',
        ),
    ]
